export default {
  'app.name': 'Alpha Match',
  'app.tagline': 'Find the right professional',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  back: 'Back',
  next: 'Next',
  submit: 'Submit',
  loading: 'Loading...',
  error: 'Something went wrong',
  retry: 'Retry',
  ok: 'OK',
  done: 'Done',
  confirm: 'Confirm',
  yes: 'Yes',
  no: 'No',
  send: 'Send',
  close: 'Close',
  search: 'Search',
};
