export default {
  'app.name': 'AlphaMatch',
  'app.tagline': 'Find the right professional',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  back: 'Back',
  next: 'Next',
  submit: 'Submit',
  continue: 'Continue',
  loading: 'Loading...',
  error: 'Something went wrong',
  retry: 'Retry',
  ok: 'OK',
  done: 'Done',
  confirm: 'Confirm',
  yes: 'Yes',
  no: 'No',
  send: 'Send',
  close: 'Close',
  search: 'Search',
  searchPlaceholder: 'Search...',
  or: 'OR',
  required: 'Required',
  optional: 'Optional',
  active: 'Active',
  uploaded: 'Uploaded',
  pending: 'Pending',
  user: 'User',
  personal: 'Personal',
  comingSoon: 'Coming Soon',
  verified: 'Verified',
  declined: 'Declined',

  // Options — Address Types
  'options.addressType.home': 'Home',
  'options.addressType.office': 'Office',
  'options.addressType.warehouse': 'Warehouse',
  'options.addressType.site': 'Site',
  'options.addressType.other': 'Other',
};
