export default {
  // Profile Screen
  'profile.title': 'Profile',
  'profile.menu': 'Menu',
  'profile.myAccount': 'My Account',
  'profile.myWallet': 'My Wallet',
  'profile.transactionHistory': 'Transaction History',
  'profile.settings': 'Settings',
  'profile.helpCenter': 'Help Center',
  'profile.termsAndConditions': 'Terms And Conditions',
  'profile.logout': 'Log Out',
  'profile.professionalAccounts': 'Your Professional Accounts',
  'profile.createAccount': 'Create Professional Account',
  'profile.noAccounts': 'You have no professional accounts yet.',
  'profile.switchToPersonal': 'Switch to Personal',
  'profile.switchToWorkspace': 'Switch Workspace',
  'profile.activeWorkspace': 'Active',
  'profile.requiredDocuments': 'Required Documents',
  'profile.addAccount': 'Add Account',
  'profile.account': 'Account',
  'profile.accountTab': 'Account',
  'profile.documentsTab': 'Documents',
  'profile.settingsTab': 'Settings',
  'profile.uploadDocument': 'Upload',
  'profile.readyToUpload': 'Ready',
  'profile.switchingTo': 'Switching to',
  'profile.documents': 'Documents',
  'profile.continueApplication': 'Continue your application',
  'profile.portfolioTab': 'Portfolio',
  'profile.addPortfolio': 'Add Project',
  'profile.projectName': 'Project Name',
  'profile.projectNamePlaceholder': 'Enter project name',
  'profile.noPortfolio': 'Showcase your best work to attract clients.',
  'profile.saveChanges': 'Save Changes',
  'profile.editProfileTitle': 'Edit Profile',
  'profile.displayName': 'Display Name',
  'profile.familyName': 'Family Name',
  'profile.phone': 'Phone',
  'profile.bio': 'Bio',
  'profile.uploadFailed': 'Failed to upload image',

  // Profile Screen — Section Labels
  'profile.switchMode': 'Switch Mode',
  'profile.personalMode': 'Client Mode',
  'profile.sectionPersonal': 'My Account',
  'profile.sectionTrading': 'Trading Account',
  'profile.sectionGlobal': 'More',
  'profile.tradingAccountActive': 'Trading account active',
  'profile.clientModeActive': 'Client mode active',

  // Profile Screen — Menu Items
  'profile.tradingAccounts': 'Trading Accounts',
  'profile.walletTransactions': 'Wallet & Transactions',
  'profile.publicProfile': 'Public Profile',
  'profile.publicProfileDesc': 'What clients see',
  'profile.verificationStatus': 'Verification Status',
  'profile.earningsWallet': 'Earnings & Wallet',
  'profile.teams': 'Teams',
  'profile.support': 'Support',
  'profile.inviteFriends': 'Invite Friends',
  'profile.appLanguage': 'App Language',

  // Settings Screen
  'settings.title': 'Settings',
  'settings.sectionAccount': 'Account',
  'settings.sectionNotifications': 'Notifications',
  'settings.sectionAppearance': 'Appearance',
  'settings.sectionDanger': 'Danger Zone',
  'settings.underConstruction': 'This settings screen is under construction.',
  'settings.privacy': 'Privacy',
  'settings.privacyDesc': 'Who can see your details',
  'settings.paymentMethods': 'Payment Methods',
  'settings.address': 'Address',
  'settings.languagesSpoken': 'Languages Spoken',
  'settings.email': 'Email',
  'settings.emailDesc': 'Change your email address',
  'settings.password': 'Password',
  'settings.passwordDesc': 'Change your password',
  'settings.trustVerification': 'Trust & Verification',
  'settings.twoFactorAuth': 'Two-Factor Authentication',
  'settings.emailNotifications': 'Email Notifications',
  'settings.pushNotifications': 'Push Notifications',
  'settings.marketingEmails': 'Marketing Emails',
  'settings.appTheme': 'App Theme',
  'settings.appThemeDesc': 'Dark / Light / Auto',
  'settings.deactivateAccount': 'Deactivate Account',
  'settings.deleteAccount': 'Delete Account',
  'settings.deactivateTitle': 'Deactivate Account',
  'settings.deactivateMessage':
    'Your account will be temporarily deactivated. You can reactivate it at any time by logging back in.',
  'settings.deactivateConfirm': 'Deactivate',
  'settings.deleteTitle': 'Delete Account',
  'settings.deleteMessage':
    'This action is permanent. All your data will be deleted and cannot be recovered.',
  'settings.deleteConfirm': 'Delete My Account',

  // Support Screen
  'support.title': 'Support',
  'support.liveChat': 'Live Chat',
  'support.liveChatDesc': 'Chat with support now',
  'support.emailSupport': 'Email Support',
  'support.emailAddress': 'support@alphamatch.com',
  'support.callSupport': 'Call Support',
  'support.callHours': 'Mon–Fri, 9am–5pm AEST',
  'support.helpCentre': 'Help Centre',
  'support.helpCentreDesc': 'Browse articles and FAQs',

  // Invite Friends Screen
  'invite.title': 'Give $20, Get $20',
  'invite.description':
    'Invite friends to AlphaMatch. When they complete their first project, you both earn $20 credit.',
  'invite.codeLabel': 'Your Invite Code',
  'invite.shareLabel': 'Share Invite Link',

  // Terms Screen
  'terms.title': 'Terms & Conditions',
  'terms.loadingUrl': 'Loading terms and conditions...',

  // Documents Screen
  'documents.title': 'Documents',
  'documents.loadError': 'Failed to load documents',
  'documents.noRequired': 'No documents required',

  // Trading Account Creation — Intro
  'ta.introTitle': 'Create Your',
  'ta.introTitleAccent': 'Professional Account',
  'ta.introSubtitle': 'Set up your professional profile and start receiving job opportunities.',
  'ta.introBenefit1': 'Get matched with relevant jobs',
  'ta.introBenefit2': 'Build your professional portfolio',
  'ta.introBenefit3': 'Manage bookings and payments',
  'ta.getStarted': 'Get Started',

  // AI Input
  'ta.aiTitle': 'Tell Us About',
  'ta.aiTitleAccent': 'Your Work',
  'ta.aiSubtitle': 'Describe what you do and we\'ll set up your profile automatically.',
  'ta.aiPlaceholder': 'e.g. I am a professional DJ based in Dubai with 5 years of experience...',
  'ta.aiAnalyze': 'Analyze & Build My Profile',
  'ta.aiManual': 'I\'ll enter details manually',
  'ta.aiCharCount': 'characters',

  // Career Selection (Manual)
  'ta.careerTitle': 'What\'s Your Ideal',
  'ta.careerTitleAccent': 'Career?',
  'ta.careerSubtitle': 'Choose the career that best describes your professional services.',
  'ta.careerPlaceholder': 'Select a career',
  'ta.careerSearch': 'Search careers...',

  // Career Confirmation
  'ta.confirmTitle': 'We Found Your',
  'ta.confirmTitleAccent': 'Career!',
  'ta.confirmSubtitle': 'Based on your description, here\'s what we detected.',
  'ta.confirmCareer': 'Detected Career',
  'ta.confirmConfidence': 'Confidence',
  'ta.confirmAlternatives': 'Other Suggestions',
  'ta.confirmAccept': 'Yes, this is correct',
  'ta.confirmChange': 'Choose a different career',
  'ta.answeredQuestions': 'Information We Extracted',
  'ta.unmatchedContent': 'Additional Details',

  // Missing Questions
  'ta.questionsTitle': 'A Few More',
  'ta.questionsTitleAccent': 'Details',
  'ta.questionsSubtitle': 'Please fill in the remaining information to complete your profile.',

  // Account Details
  'ta.detailsTitle': 'Setting Up Your',
  'ta.detailsTitleAccent': 'Profile',
  'ta.detailsSubtitle': 'Add your professional details.',
  'ta.accountName': 'Profile Name',
  'ta.accountNamePlaceholder': 'e.g. Elite DJ Services',
  'ta.bio': 'Bio',
  'ta.bioPlaceholder': 'Tell clients about yourself...',
  'ta.general': 'General',
  'ta.contact': 'Contact',
  'ta.address': 'Address',
  'ta.email': 'Email',
  'ta.phone': 'Phone',
  'ta.phonePlaceholder': 'Enter phone number',
  'ta.addressField': 'Address',
  'ta.addressPlaceholder': 'Enter your address',
  'ta.city': 'City',
  'ta.postalCode': 'Postal Code',
  'ta.postalCodePlaceholder': 'Enter postal code',
  'ta.uploadPhoto': 'Upload Photo',

  // Portfolio
  'ta.portfolioTitle': 'Add Your',
  'ta.portfolioTitleAccent': 'Portfolio',
  'ta.portfolioSubtitle': 'Showcase your best work to attract clients.',
  'ta.projectName': 'Project Name',
  'ta.projectNamePlaceholder': 'Enter project name',
  'ta.chooseFile': 'Choose File to',
  'ta.upload': 'Upload',
  'ta.addMore': 'Add More',

  // Verification (Pro)
  'ta.verificationTitle': 'Verify Your',
  'ta.verificationTitleAccent': 'Identity',
  'ta.verificationSubtitle': 'Upload the required documents to verify your account.',
  'ta.uploadDocument': 'Upload Document',
  'ta.documentRequired': 'Required',
  'ta.documentOptional': 'Optional',

  // Subscription (Flex)
  'ta.subscriptionTitle': 'Pick Your',
  'ta.subscriptionTitleAccent': 'Plan',
  'ta.subscriptionSubtitle': 'Choose a subscription plan to activate your account.',
  'ta.perMonth': '/month',
  'ta.startTrial': 'Start Free Trial',
  'ta.subscribe': 'Subscribe Now',
  'ta.trialDays': 'day free trial',

  // Completion
  'ta.completeTitle': 'You\'re All',
  'ta.completeTitleAccent': 'Set!',
  'ta.completeSubtitle': 'Your professional account has been created successfully.',
  'ta.goToWorkspace': 'Go to Workspace',
  'ta.stayPersonal': 'Stay in Personal Mode',

  // Common
  'ta.continue': 'Continue',
  'ta.skip': 'Skip',
  'ta.back': 'Back',
  'ta.step': 'Step',
  'ta.of': 'of',

  // Portfolio Screen
  'profile.portfolio.title': 'Portfolio',
  'profile.portfolio.addButton': 'Add Project',
  'profile.portfolio.updateButton': 'Update',
  'profile.portfolio.addTitle': 'Add Project',
  'profile.portfolio.editTitle': 'Edit Project',
  'profile.portfolio.emptyTitle': 'No portfolio projects yet',
  'profile.portfolio.emptyDescription': 'Showcase your best work by adding projects to your portfolio.',
  'profile.portfolio.deleteConfirmTitle': 'Delete Portfolio Item',
  'profile.portfolio.deleteConfirmMessage': 'Are you sure you want to delete this project?',
  'profile.portfolio.cancel': 'Cancel',
  'profile.portfolio.delete': 'Delete',
  'profile.portfolio.dateFrom': 'From',
  'profile.portfolio.dateUntil': 'Until',
  'profile.portfolio.addAccessibility': 'Add portfolio project',
  'profile.portfolio.editAccessibility': 'Edit portfolio project',
  'profile.portfolio.deleteAccessibility': 'Delete portfolio project',
  'profile.portfolio.validation.titleRequired': 'Title is required',
  'profile.portfolio.fields.title': 'Title',
  'profile.portfolio.fields.titlePlaceholder': 'e.g. Kitchen Renovation — Bondi',
  'profile.portfolio.fields.description': 'Description',
  'profile.portfolio.fields.descriptionPlaceholder': 'Describe the project, scope, and your role',
  'profile.portfolio.fields.startDate': 'Start Date',
  'profile.portfolio.fields.endDate': 'End Date',
  'profile.portfolio.fields.projectLink': 'Project Link',

  // Experience Screen
  'profile.experience.title': 'Experience',
  'profile.experience.addButton': 'Add Experience',
  'profile.experience.updateButton': 'Update Experience',
  'profile.experience.addTitle': 'Add Experience',
  'profile.experience.editTitle': 'Edit Experience',
  'profile.experience.emptyTitle': 'No experience added yet',
  'profile.experience.emptyDescription': 'Add your work history to showcase your professional background.',
  'profile.experience.deleteConfirmTitle': 'Delete Experience',
  'profile.experience.deleteConfirmMessage': 'Are you sure you want to delete this experience?',
  'profile.experience.cancel': 'Cancel',
  'profile.experience.delete': 'Delete',
  'profile.experience.addAccessibility': 'Add experience',
  'profile.experience.addHint': 'Opens the form to add a new experience',
  'profile.experience.editAccessibility': 'Edit experience',
  'profile.experience.editHint': 'Opens the edit form for this experience',
  'profile.experience.deleteAccessibility': 'Delete experience',
  'profile.experience.deleteHint': 'Deletes this experience entry',
  'profile.experience.validation.title': 'Validation',
  'profile.experience.validation.jobTitleRequired': 'Job title is required.',
  'profile.experience.validation.companyRequired': 'Company is required.',
  'profile.experience.validation.startMonthInvalid': 'Start month must be between 1 and 12.',
  'profile.experience.validation.startYearRequired': 'Start year is required.',
  'profile.experience.fields.jobTitle': 'Job Title',
  'profile.experience.fields.jobTitlePlaceholder': 'e.g. Senior Electrician',
  'profile.experience.fields.company': 'Company',
  'profile.experience.fields.companyPlaceholder': 'e.g. ABC Electrical',
  'profile.experience.fields.country': 'Country',
  'profile.experience.fields.countryPlaceholder': 'e.g. Australia',
  'profile.experience.fields.city': 'City',
  'profile.experience.fields.cityPlaceholder': 'e.g. Sydney',
  'profile.experience.fields.startMonth': 'Start Month',
  'profile.experience.fields.startYear': 'Start Year',
  'profile.experience.fields.endMonth': 'End Month',
  'profile.experience.fields.endYear': 'End Year',
  'profile.experience.fields.monthPlaceholder': '1-12',
  'profile.experience.fields.yearPlaceholder': 'e.g. 2020',
  'profile.experience.fields.currentlyWorkHere': 'I currently work here',
  'profile.experience.fields.description': 'Description',
  'profile.experience.fields.descriptionPlaceholder': 'Describe your responsibilities...',

  // Education Screen
  'profile.education.title': 'Education',
  'profile.education.addButton': 'Add Education',
  'profile.education.updateButton': 'Update Education',
  'profile.education.addTitle': 'Add Education',
  'profile.education.editTitle': 'Edit Education',
  'profile.education.emptyTitle': 'No education added yet',
  'profile.education.emptyDescription': 'Add your educational background to strengthen your profile.',
  'profile.education.deleteConfirmTitle': 'Delete Education',
  'profile.education.deleteConfirmMessage': 'Are you sure you want to delete this education entry?',
  'profile.education.cancel': 'Cancel',
  'profile.education.delete': 'Delete',
  'profile.education.addAccessibility': 'Add education',
  'profile.education.addHint': 'Opens the form to add a new education entry',
  'profile.education.editAccessibility': 'Edit education',
  'profile.education.editHint': 'Opens the edit form for this education entry',
  'profile.education.deleteAccessibility': 'Delete education',
  'profile.education.deleteHint': 'Deletes this education entry',
  'profile.education.validation.title': 'Validation',
  'profile.education.validation.institutionRequired': 'Institution is required.',
  'profile.education.validation.degreeRequired': 'Degree is required.',
  'profile.education.validation.startYearRequired': 'Start year is required.',
  'profile.education.fields.country': 'Country',
  'profile.education.fields.countryPlaceholder': 'e.g. Australia',
  'profile.education.fields.institution': 'Institution',
  'profile.education.fields.institutionPlaceholder': 'e.g. University of Sydney',
  'profile.education.fields.degree': 'Degree',
  'profile.education.fields.degreePlaceholder': 'e.g. Bachelor of Engineering',
  'profile.education.fields.startYear': 'Start Year',
  'profile.education.fields.startYearPlaceholder': 'e.g. 2018',
  'profile.education.fields.endYear': 'End Year',
  'profile.education.fields.endYearPlaceholder': 'e.g. 2022',

  // Qualifications Screen
  'profile.qualifications.title': 'Qualifications',
  'profile.qualifications.addButton': 'Add Qualification',
  'profile.qualifications.updateButton': 'Update',
  'profile.qualifications.addTitle': 'Add Qualification',
  'profile.qualifications.editTitle': 'Edit Qualification',
  'profile.qualifications.emptyTitle': 'No qualifications added yet',
  'profile.qualifications.emptyDescription': 'Add certifications and awards to highlight your expertise.',
  'profile.qualifications.deleteConfirmTitle': 'Delete Qualification',
  'profile.qualifications.deleteConfirmMessage': 'Are you sure you want to delete this qualification?',
  'profile.qualifications.cancel': 'Cancel',
  'profile.qualifications.delete': 'Delete',
  'profile.qualifications.addAccessibility': 'Add qualification',
  'profile.qualifications.editAccessibility': 'Edit qualification',
  'profile.qualifications.deleteAccessibility': 'Delete qualification',
  'profile.qualifications.validation.titleRequired': 'Certificate/award name is required',
  'profile.qualifications.validation.organisationRequired': 'Organisation is required',
  'profile.qualifications.validation.yearRequired': 'Year is required',
  'profile.qualifications.fields.certificateName': 'Certificate/Award Name',
  'profile.qualifications.fields.certificateNamePlaceholder': 'e.g. AWS Certified Solutions Architect',
  'profile.qualifications.fields.organisation': 'Conferring Organisation',
  'profile.qualifications.fields.organisationPlaceholder': 'e.g. Amazon Web Services',
  'profile.qualifications.fields.summary': 'Summary',
  'profile.qualifications.fields.summaryPlaceholder': 'Brief description of the qualification',
  'profile.qualifications.fields.year': 'Year',
  'profile.qualifications.fields.yearPlaceholder': 'e.g. 2023',

  // References Screen
  'profile.references.title': 'References',
  'profile.references.addButton': 'Add Reference',
  'profile.references.updateButton': 'Update',
  'profile.references.addTitle': 'Add Reference',
  'profile.references.editTitle': 'Edit Reference',
  'profile.references.emptyTitle': 'No references added yet',
  'profile.references.emptyDescription': 'Add professional references to build trust with potential clients.',
  'profile.references.deleteConfirmTitle': 'Delete Reference',
  'profile.references.deleteConfirmMessage': 'Are you sure you want to delete this reference?',
  'profile.references.cancel': 'Cancel',
  'profile.references.delete': 'Delete',
  'profile.references.addAccessibility': 'Add reference',
  'profile.references.editAccessibility': 'Edit reference',
  'profile.references.deleteAccessibility': 'Delete reference',
  'profile.references.validation.fullNameRequired': 'Full name is required',
  'profile.references.validation.relationshipRequired': 'Relationship is required',
  'profile.references.validation.contactRequired': 'Email or phone is required',
  'profile.references.validation.companyRequired': 'Company is required for this relationship',
  'profile.references.validation.jobTitleRequired': 'Job title is required for this relationship',
  'profile.references.relationship.manager': 'Manager',
  'profile.references.relationship.colleague': 'Colleague',
  'profile.references.relationship.client': 'Client',
  'profile.references.relationship.friend': 'Friend',
  'profile.references.relationship.other': 'Other',
  'profile.references.fields.fullName': 'Full Name',
  'profile.references.fields.fullNamePlaceholder': 'e.g. John Smith',
  'profile.references.fields.relationship': 'Relationship',
  'profile.references.fields.email': 'Email',
  'profile.references.fields.emailPlaceholder': 'john@example.com',
  'profile.references.fields.phone': 'Phone',
  'profile.references.fields.phonePlaceholder': '+61 400 000 000',
  'profile.references.fields.company': 'Company',
  'profile.references.fields.companyPlaceholder': 'e.g. Acme Corp',
  'profile.references.fields.jobTitle': 'Job Title',
  'profile.references.fields.jobTitlePlaceholder': 'e.g. Senior Developer',
  'profile.references.fields.knownSince': 'Known Since',
  'profile.references.fields.knownSincePlaceholder': 'e.g. Since 2019',

  // ── Edit Profile Form ──
  'profile.fields.firstName': 'First Name',
  'profile.fields.firstNamePlaceholder': 'Enter first name',
  'profile.fields.firstNameRequired': 'First name is required',
  'profile.fields.middleName': 'Middle Name',
  'profile.fields.middleNamePlaceholder': 'Enter middle name',
  'profile.fields.lastName': 'Last Name',
  'profile.fields.lastNamePlaceholder': 'Enter last name',
  'profile.fields.lastNameRequired': 'Last name is required',
  'profile.fields.phoneNumber': 'Contact Phone',
  'profile.fields.phoneNumberPlaceholder': 'Enter phone number',
  'profile.fields.countryCode': 'Code',
  'profile.fields.bio': 'Bio',
  'profile.fields.bioPlaceholder': 'Tell us about yourself',
  'profile.fields.gender': 'Gender',
  'profile.fields.genderPlaceholder': 'Select gender',
  'profile.fields.birthDate': 'Date of Birth',
  'profile.fields.birthDatePlaceholder': 'Select date of birth',
  'profile.fields.nationality': 'Nationality',
  'profile.fields.nationalityPlaceholder': 'e.g. Australian',
  'profile.fields.languages': 'Languages',
  'profile.fields.languageName': 'Language',
  'profile.fields.languageNamePlaceholder': 'e.g. English, Arabic',
  'profile.fields.proficiency': 'Proficiency',
  'profile.fields.isNative': 'Native',
  'profile.gender.male': 'Male',
  'profile.gender.female': 'Female',
  'profile.proficiency.beginner': 'Beginner',
  'profile.proficiency.intermediate': 'Intermediate',
  'profile.proficiency.advanced': 'Advanced',
  'profile.proficiency.fluent': 'Fluent',

  // ── Edit Profile — Address Section ──
  'profile.address.title': 'Addresses',
  'profile.address.type': 'Type',
  'profile.address.typeRequired': 'Type is required',
  'profile.address.address': 'Address',
  'profile.address.searchPlaceholder': 'Search for address',
  'profile.address.manualEntry': 'Enter address manually',
  'profile.address.street': 'Street Address',
  'profile.address.streetPlaceholder': 'Enter street address',
  'profile.address.streetRequired': 'Street is required',
  'profile.address.state': 'State / Region',
  'profile.address.statePlaceholder': 'Enter state',
  'profile.address.city': 'City',
  'profile.address.cityPlaceholder': 'Enter city',
  'profile.address.cityRequired': 'City is required',
  'profile.address.postcode': 'Postcode',
  'profile.address.postcodePlaceholder': 'Postcode',
};
