export default {
  // Profile Screen
  'profile.title': 'Profile',
  'profile.menu': 'Menu',
  'profile.myAccount': 'My Account',
  'profile.myWallet': 'My Wallet',
  'profile.transactionHistory': 'Transaction History',
  'profile.settings': 'Settings',
  'profile.helpCenter': 'Help Center',
  'profile.termsAndConditions': 'Terms And Conditions',
  'profile.logout': 'Log Out',
  'profile.professionalAccounts': 'Your Professional Accounts',
  'profile.createAccount': 'Create Professional Account',
  'profile.noAccounts': 'You have no professional accounts yet.',
  'profile.switchToPersonal': 'Switch to Personal',
  'profile.switchToWorkspace': 'Switch Workspace',
  'profile.activeWorkspace': 'Active',
  'profile.requiredDocuments': 'Required Documents',
  'profile.addAccount': 'Add Account',
  'profile.account': 'Account',
  'profile.accountTab': 'Account',
  'profile.documentsTab': 'Documents',
  'profile.settingsTab': 'Settings',
  'profile.uploadDocument': 'Upload',
  'profile.readyToUpload': 'Ready',
  'profile.switchingTo': 'Switching to',
  'profile.documents': 'Documents',
  'profile.continueApplication': 'Continue your application',
  'profile.portfolioTab': 'Portfolio',
  'profile.addPortfolio': 'Add Project',
  'profile.projectName': 'Project Name',
  'profile.projectNamePlaceholder': 'Enter project name',
  'profile.noPortfolio': 'Showcase your best work to attract clients.',

  // Trading Account Creation — Intro
  'ta.introTitle': 'Create Your',
  'ta.introTitleAccent': 'Professional Account',
  'ta.introSubtitle': 'Set up your professional profile and start receiving job opportunities.',
  'ta.introBenefit1': 'Get matched with relevant jobs',
  'ta.introBenefit2': 'Build your professional portfolio',
  'ta.introBenefit3': 'Manage bookings and payments',
  'ta.getStarted': 'Get Started',

  // AI Input
  'ta.aiTitle': 'Tell Us About',
  'ta.aiTitleAccent': 'Your Work',
  'ta.aiSubtitle': 'Describe what you do and we\'ll set up your profile automatically.',
  'ta.aiPlaceholder': 'e.g. I am a professional DJ based in Dubai with 5 years of experience...',
  'ta.aiAnalyze': 'Analyze & Build My Profile',
  'ta.aiManual': 'I\'ll enter details manually',
  'ta.aiCharCount': 'characters',

  // Career Selection (Manual)
  'ta.careerTitle': 'What\'s Your Ideal',
  'ta.careerTitleAccent': 'Career?',
  'ta.careerSubtitle': 'Choose the career that best describes your professional services.',
  'ta.careerPlaceholder': 'Select a career',
  'ta.careerSearch': 'Search careers...',

  // Career Confirmation
  'ta.confirmTitle': 'We Found Your',
  'ta.confirmTitleAccent': 'Career!',
  'ta.confirmSubtitle': 'Based on your description, here\'s what we detected.',
  'ta.confirmCareer': 'Detected Career',
  'ta.confirmConfidence': 'Confidence',
  'ta.confirmAlternatives': 'Other Suggestions',
  'ta.confirmAccept': 'Yes, this is correct',
  'ta.confirmChange': 'Choose a different career',
  'ta.answeredQuestions': 'Information We Extracted',
  'ta.unmatchedContent': 'Additional Details',

  // Missing Questions
  'ta.questionsTitle': 'A Few More',
  'ta.questionsTitleAccent': 'Details',
  'ta.questionsSubtitle': 'Please fill in the remaining information to complete your profile.',

  // Account Details
  'ta.detailsTitle': 'Setting Up Your',
  'ta.detailsTitleAccent': 'Profile',
  'ta.detailsSubtitle': 'Add your professional details.',
  'ta.accountName': 'Profile Name',
  'ta.accountNamePlaceholder': 'e.g. Elite DJ Services',
  'ta.bio': 'Bio',
  'ta.bioPlaceholder': 'Tell clients about yourself...',
  'ta.general': 'General',
  'ta.contact': 'Contact',
  'ta.address': 'Address',
  'ta.email': 'Email',
  'ta.phone': 'Phone',
  'ta.phonePlaceholder': 'Enter phone number',
  'ta.addressField': 'Address',
  'ta.addressPlaceholder': 'Enter your address',
  'ta.city': 'City',
  'ta.postalCode': 'Postal Code',
  'ta.postalCodePlaceholder': 'Enter postal code',
  'ta.uploadPhoto': 'Upload Photo',

  // Portfolio
  'ta.portfolioTitle': 'Add Your',
  'ta.portfolioTitleAccent': 'Portfolio',
  'ta.portfolioSubtitle': 'Showcase your best work to attract clients.',
  'ta.projectName': 'Project Name',
  'ta.projectNamePlaceholder': 'Enter project name',
  'ta.chooseFile': 'Choose File to',
  'ta.upload': 'Upload',
  'ta.addMore': 'Add More',

  // Verification (Pro)
  'ta.verificationTitle': 'Verify Your',
  'ta.verificationTitleAccent': 'Identity',
  'ta.verificationSubtitle': 'Upload the required documents to verify your account.',
  'ta.uploadDocument': 'Upload Document',
  'ta.documentRequired': 'Required',
  'ta.documentOptional': 'Optional',

  // Subscription (Flex)
  'ta.subscriptionTitle': 'Pick Your',
  'ta.subscriptionTitleAccent': 'Plan',
  'ta.subscriptionSubtitle': 'Choose a subscription plan to activate your account.',
  'ta.perMonth': '/month',
  'ta.startTrial': 'Start Free Trial',
  'ta.subscribe': 'Subscribe Now',
  'ta.trialDays': 'day free trial',

  // Completion
  'ta.completeTitle': 'You\'re All',
  'ta.completeTitleAccent': 'Set!',
  'ta.completeSubtitle': 'Your professional account has been created successfully.',
  'ta.goToWorkspace': 'Go to Workspace',
  'ta.stayPersonal': 'Stay in Personal Mode',

  // Common
  'ta.continue': 'Continue',
  'ta.skip': 'Skip',
  'ta.back': 'Back',
  'ta.step': 'Step',
  'ta.of': 'of',
};
