import type { IColumnBase, IDataTableProps, IDatatableRefValues, IPaginationRequest, PaginationState, ServerResponse, IPaginationResponse } from "@lmb/kitsconcerto-types";
import { type DataTableExpandedRows, type DataTableFilterMeta, type DataTableStateEvent, type DataTableValueArray, type DataTable as PrimeTableType } from "primereact/datatable";
import { type PaginatorPageChangeEvent } from "primereact/paginator";
export declare function buildFiltersDefault(columns: IDataTableProps["columns"]): DataTableFilterMeta;
export declare function useTableState<T extends Record<string, any> = any>(props: IDataTableProps<T>, ref: IDataTableProps<T>["ref"]): {
    tableRef: import("react").RefObject<PrimeTableType<T[]>>;
    refValues: IDatatableRefValues<T>;
    isLoading: boolean;
    dataList: T[];
    globalFilterValue: string;
    visibleColumns: Pick<IColumnBase, "label" | "name">[];
    expandedRows: DataTableValueArray | DataTableExpandedRows;
    setExpandedRows: import("react").Dispatch<import("react").SetStateAction<DataTableValueArray | DataTableExpandedRows>>;
    isSelectable: boolean;
    selections: T[];
    setSelections: import("react").Dispatch<import("react").SetStateAction<T[]>>;
    serverSideRequest: IPaginationRequest;
    lockedRows: T[];
    filtersDefault: DataTableFilterMeta;
    isAnyFilter: boolean;
    allowExpansion: boolean;
    pagination: PaginationState;
    conditionalProps: import("primereact/datatable").DataTablePropsSingle<T[]>;
    refresh: (withLoading?: boolean) => void;
    onColumnToggle: (selectedNames: string[]) => void;
    onChangePage: (event: PaginatorPageChangeEvent) => void;
    onChangeFilter: (event: DataTableStateEvent) => void;
    onChangeSort: (event: DataTableStateEvent) => void;
    onGlobalFilterChange: (value: string) => void;
    onClearFilter: () => void;
    onClearCache: () => void;
    toggleLock: (rowData: T, frozen: boolean | undefined, index: number) => void;
    columns: import("@lmb/kitsconcerto-types").IColumn<T>[];
    onRowSelect: any;
    onSelectChange: (event: import("@lmb/kitsconcerto-types").DataTableSelectionSingleChangeEvent<T[]>) => void;
    selectionMode: any;
    tableSize: "small" | "normal" | "large";
    resizableColumns: any;
    scrollHeight: string;
    stateful: boolean;
    skeleton: boolean;
    globalSearch: boolean;
    headless: boolean;
    multiSorting: boolean;
    rowLockable: boolean;
    rowExpansionTemplate: any;
    service: (paginationRequest: IPaginationRequest) => Promise<ServerResponse<IPaginationResponse<T[]>>>;
    keyColumn: string;
    staticData: T[];
    exportPDFButton: boolean;
    exportCSVButton: boolean;
    moreButtons: (context: IDatatableRefValues<T>) => import("react").ReactNode[];
    tableTitle: string;
    debounceFilterWaitTime: number;
};
//# sourceMappingURL=useTableState.d.ts.map