import React, { type ReactNode } from 'react';
import type { IButtonProps, IButtonState } from '@lmb/kitsconcerto-types';
export declare function useButton(props: IButtonProps<any>): {
    state: IButtonState;
    handlers: {
        onClick: React.MouseEventHandler<any>;
        onPressIn: () => void;
        onPressOut: () => void;
        onMouseEnter: () => void;
        onMouseLeave: () => void;
    };
    _nativeProps: {
        id?: string;
        type?: "submit" | "button";
        ref?: React.Ref<any>;
        children?: string | ReactNode;
        severity?: "secondary" | "success" | "info" | "warning" | "help" | "danger" | "contrast" | undefined;
        icon?: any;
        iconPos?: "left" | "right" | "top" | "bottom";
        size?: "sm" | "md" | "lg";
        outlined?: boolean;
        raised?: boolean;
        rounded?: boolean;
        label?: string;
        isLoadingText?: string;
        tooltip?: string;
        tooltipOptions?: {
            position?: string;
        };
        style?: import("@lmb/kitsconcerto-types").IStyleClasses;
        className?: string;
        testID?: string;
        p?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        padding?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        pt?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingTop"] | `${number}${string}`>;
        paddingTop?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingTop"] | `${number}${string}`>;
        pr?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingRight"] | `${number}${string}`>;
        paddingRight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingRight"] | `${number}${string}`>;
        pb?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingBottom"] | `${number}${string}`>;
        paddingBottom?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingBottom"] | `${number}${string}`>;
        pl?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingLeft"] | `${number}${string}`>;
        paddingLeft?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["paddingLeft"] | `${number}${string}`>;
        px?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        paddingX?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        py?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        paddingY?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        paddingHorizontal?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        paddingVertical?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["padding"] | `${number}${string}`>;
        m?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        margin?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        mt?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginTop"] | `${number}${string}`>;
        marginTop?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginTop"] | `${number}${string}`>;
        mr?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginRight"] | `${number}${string}`>;
        marginRight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginRight"] | `${number}${string}`>;
        mb?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginBottom"] | `${number}${string}`>;
        marginBottom?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginBottom"] | `${number}${string}`>;
        ml?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginLeft"] | `${number}${string}`>;
        marginLeft?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["marginLeft"] | `${number}${string}`>;
        mx?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        marginX?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        my?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        marginY?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["margin"] | `${number}${string}`>;
        marginInline?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | `${number}${string}`>;
        w?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["width"] | "full" | "screen" | string | `${number}${string}`>;
        width?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["width"] | "full" | "screen" | string | `${number}${string}`>;
        minW?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["minWidth"] | "full" | "screen" | string | `${number}${string}`>;
        minWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["minWidth"] | "full" | "screen" | string | `${number}${string}`>;
        maxW?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["maxWidth"] | "full" | "screen" | string | `${number}${string}`>;
        maxWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["maxWidth"] | "full" | "screen" | string | `${number}${string}`>;
        h?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["height"] | "full" | "screen" | string | `${number}${string}`>;
        height?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["height"] | "full" | "screen" | string | `${number}${string}`>;
        minH?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["minHeight"] | "full" | "screen" | string | `${number}${string}`>;
        minHeight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["minHeight"] | "full" | "screen" | string | `${number}${string}`>;
        maxH?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["maxHeight"] | "full" | "screen" | string | `${number}${string}`>;
        maxHeight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["maxHeight"] | "full" | "screen" | string | `${number}${string}`>;
        borderRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderRadius"]>;
        borderRadiusTop?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopLeftRadius"] | import("react-native").ViewStyle["borderTopRightRadius"]>;
        borderRadiusBottom?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderBottomLeftRadius"] | import("react-native").ViewStyle["borderBottomRightRadius"]>;
        borderRadiusRight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopRightRadius"] | import("react-native").ViewStyle["borderBottomRightRadius"]>;
        borderRadiusLeft?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopLeftRadius"] | import("react-native").ViewStyle["borderBottomLeftRadius"]>;
        borderTopLeftRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopLeftRadius"]>;
        borderBottomLeftRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderBottomLeftRadius"]>;
        borderTopRightRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopRightRadius"]>;
        borderBottomRightRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderBottomRightRadius"]>;
        borderWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderWidth"]>;
        borderW?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderWidth"]>;
        borderX?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderLeftWidth"] | import("react-native").ViewStyle["borderRightWidth"]>;
        borderY?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopWidth"] | import("react-native").ViewStyle["borderBottomWidth"]>;
        borderTop?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopWidth"]>;
        borderBottom?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderBottomWidth"]>;
        borderRight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderRightWidth"]>;
        borderLeft?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderLeftWidth"]>;
        borderStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderStyle"]>;
        borderColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderColor"] | import("@lmb/kitsconcerto-types").ColorValue | import("react-native").ColorValue>;
        borderStartStartRadius?: null;
        borderStartEndRadius?: null;
        borderEndStartRadius?: null;
        borderEndEndRadius?: null;
        borderCollapse?: null;
        borderSpacing?: null;
        border?: null | "none";
        borderBlock?: null;
        borderBlockColor?: null;
        borderBlockStyle?: null;
        borderBlockWidth?: null;
        borderBlockEnd?: null;
        borderBlockStart?: null;
        borderInline?: null;
        borderInlineColor?: null;
        borderInlineStyle?: null;
        borderInlineWidth?: null;
        borderInlineEnd?: null;
        borderInlineStart?: null;
        borderTopColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderColor"]>;
        borderTopStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderStyle"]>;
        borderTopWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderTopWidth"]>;
        borderBottomColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderColor"]>;
        borderBottomStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderStyle"]>;
        borderBottomWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderBottomWidth"]>;
        borderLeftColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderColor"]>;
        borderLeftStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderStyle"]>;
        borderLeftWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderLeftWidth"]>;
        borderRightColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderColor"]>;
        borderRightStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderStyle"]>;
        borderRightWidth?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["borderRightWidth"]>;
        backgroundColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("@lmb/kitsconcerto-types").ColorValue | import("react-native").ColorValue>;
        bgColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("@lmb/kitsconcerto-types").ColorValue | import("react-native").ColorValue>;
        backgroundImage?: null;
        bgImage?: null;
        backgroundRepeat?: null;
        bgRepeat?: null;
        backgroundSize?: null;
        bgSize?: null;
        backgroundPosition?: null;
        bgPosition?: null;
        gap?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        rowGap?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        columnGap?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        flex?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        flexDirection?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"row" | "column" | "row-reverse" | "column-reverse">;
        direction?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"row" | "column" | "row-reverse" | "column-reverse">;
        flexWrap?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"wrap" | "nowrap" | "wrap-reverse">;
        flexGrow?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        flexShrink?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        flexBasis?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        flexOrder?: null;
        templateAreas?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        gridTemplateRows?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        gridTemplateColumns?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        columns?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        rows?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        area?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        rowSpan?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        rowOffset?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        colSpan?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        colOffset?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("@lmb/kitsconcerto-types").Numbering0_12>;
        rowStart?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        rowEnd?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        colStart?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        colEnd?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        boxShadow?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowColor"] | import("react-native").ViewStyle["shadowOffset"] | import("react-native").ViewStyle["shadowOpacity"] | import("react-native").ViewStyle["shadowRadius"]>;
        shadow?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowColor"] | import("react-native").ViewStyle["shadowOffset"] | import("react-native").ViewStyle["shadowOpacity"] | import("react-native").ViewStyle["shadowRadius"]>;
        opacity?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["opacity"]>;
        shadowColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowColor"]>;
        shadowOffset?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowOffset"]>;
        shadowRadius?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowRadius"]>;
        shadowOpacity?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["shadowOpacity"]>;
        elevation?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["elevation"]>;
        objectFit?: any;
        objectPosition?: any;
        appearance?: null;
        cursor?: any;
        outline?: null;
        pointerEvents?: import("react-native").ViewStyle["pointerEvents"];
        userSelect?: any;
        translateX?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        translateY?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        translate?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        transformOrigin?: null;
        rotate?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"0deg" | "90deg" | "-90deg" | "180deg" | "-180deg">;
        transitionProperty?: null;
        transitionDuration?: null;
        transitionFunction?: null;
        transitionDelay?: null;
        display?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["display"]>;
        overflow?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["overflow"] | "auto">;
        overflowY?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"visible" | "hidden">;
        overflowX?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"visible" | "hidden">;
        position?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["position"] | "fixed" | "sticky">;
        top?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["top"]>;
        bottom?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["bottom"]>;
        right?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["right"]>;
        left?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["left"]>;
        zIndex?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("react-native").ViewStyle["zIndex"]>;
        aspectRatio?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        transition?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        animation?: import("@lmb/kitsconcerto-types").AnimationsValues;
        animationDuration?: import("@lmb/kitsconcerto-types").TimingNumbering | 2000 | 3000;
        animationDelay?: import("@lmb/kitsconcerto-types").TimingNumbering;
        animationIteration?: "linear" | "ease-in" | "ease-out" | "ease-in-out";
        animationFunction?: "auto" | 0 | 50 | 100;
        animationFill?: "none" | "forwards" | "backwards" | "both";
        justifyContent?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "space-evenly">;
        alignContent?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "stretch">;
        alignItems?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"flex-start" | "flex-end" | "center" | "stretch" | "baseline">;
        alignSelf?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"auto" | "flex-start" | "flex-end" | "center" | "stretch" | "baseline">;
        verticalAlign?: any;
        listStyleType?: null;
        listStyle?: null;
        letterSpacing?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | string>;
        fontSize?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | "base" | Omit<import("@lmb/kitsconcerto-types").SizingValue, "md"> | import("@lmb/kitsconcerto-types").HighSizingValue>;
        fontWeight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"normal" | "bold" | "light" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900">;
        fontColor?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<import("@lmb/kitsconcerto-types").ColorValue | import("react-native").ColorValue | string>;
        fontFamily?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<string>;
        fontStyle?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"normal" | "italic">;
        textAlign?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<"auto" | "left" | "right" | "center" | "justify">;
        textDecoration?: "underline" | "line-through" | "none";
        textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
        lineHeight?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number | `${number}${string}`>;
        textOverflow?: "ellipsis" | "clip" | null;
        whiteSpace?: "nowrap" | "normal" | null;
        numberOfLines?: import("@lmb/kitsconcerto-types").KitsResponsiveValue<number>;
        _hover?: import("@lmb/kitsconcerto-types").ICssStyling;
    };
    isDisabled: boolean;
};
//# sourceMappingURL=useButton.d.ts.map