export default {
  'app.name': 'ألفا ماتش',
  'app.tagline': 'ابحث عن المحترف المناسب',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  edit: 'تعديل',
  back: 'رجوع',
  next: 'التالي',
  submit: 'إرسال',
  loading: '...جاري التحميل',
  error: 'حدث خطأ',
  retry: 'إعادة المحاولة',
  ok: 'حسنًا',
  done: 'تم',
  confirm: 'تأكيد',
  yes: 'نعم',
  no: 'لا',
  send: 'إرسال',
  close: 'إغلاق',
  search: 'بحث',

  // Options — Address Types
  'options.addressType.home': 'المنزل',
  'options.addressType.office': 'المكتب',
  'options.addressType.warehouse': 'المستودع',
  'options.addressType.site': 'الموقع',
  'options.addressType.other': 'أخرى',
};
