export default {
  // Profile Screen
  'profile.title': 'الملف الشخصي',
  'profile.menu': 'القائمة',
  'profile.myAccount': 'حسابي',
  'profile.myWallet': 'محفظتي',
  'profile.transactionHistory': 'سجل المعاملات',
  'profile.settings': 'الإعدادات',
  'profile.helpCenter': 'مركز المساعدة',
  'profile.termsAndConditions': 'الشروط والأحكام',
  'profile.logout': 'تسجيل الخروج',
  'profile.professionalAccounts': 'حساباتك المهنية',
  'profile.createAccount': 'إنشاء حساب مهني',
  'profile.noAccounts': 'ليس لديك حسابات مهنية بعد.',
  'profile.switchToPersonal': 'التبديل إلى الشخصي',
  'profile.switchToWorkspace': 'تبديل مساحة العمل',
  'profile.activeWorkspace': 'نشط',
  'profile.requiredDocuments': 'المستندات المطلوبة',
  'profile.addAccount': 'إضافة حساب',
  'profile.account': 'الحساب',
  'profile.accountTab': 'الحساب',
  'profile.documentsTab': 'المستندات',
  'profile.settingsTab': 'الإعدادات',
  'profile.uploadDocument': 'رفع',
  'profile.readyToUpload': 'جاهز',
  'profile.switchingTo': 'التبديل إلى',
  'profile.documents': 'المستندات',
  'profile.continueApplication': 'أكمل طلبك',
  'profile.portfolioTab': 'معرض الأعمال',
  'profile.addPortfolio': 'إضافة مشروع',
  'profile.projectName': 'اسم المشروع',
  'profile.projectNamePlaceholder': 'أدخل اسم المشروع',
  'profile.noPortfolio': 'اعرض أفضل أعمالك لجذب العملاء.',

  // Trading Account Creation — Intro
  'ta.introTitle': 'أنشئ حسابك',
  'ta.introTitleAccent': 'المهني',
  'ta.introSubtitle': 'أعد ملفك المهني وابدأ في تلقي فرص العمل.',
  'ta.introBenefit1': 'احصل على عروض عمل مناسبة',
  'ta.introBenefit2': 'ابنِ معرض أعمالك المهني',
  'ta.introBenefit3': 'أدر حجوزاتك ومدفوعاتك',
  'ta.getStarted': 'ابدأ الآن',

  // AI Input
  'ta.aiTitle': 'أخبرنا عن',
  'ta.aiTitleAccent': 'عملك',
  'ta.aiSubtitle': 'صف ما تفعله وسنقوم بإعداد ملفك تلقائيًا.',
  'ta.aiPlaceholder': 'مثال: أنا دي جي محترف في دبي مع خبرة 5 سنوات...',
  'ta.aiAnalyze': 'تحليل وبناء ملفي',
  'ta.aiManual': 'سأدخل التفاصيل يدويًا',
  'ta.aiCharCount': 'حرف',

  // Career Selection (Manual)
  'ta.careerTitle': 'ما هي مهنتك',
  'ta.careerTitleAccent': 'المثالية؟',
  'ta.careerSubtitle': 'اختر المهنة التي تصف خدماتك المهنية بأفضل شكل.',
  'ta.careerPlaceholder': 'اختر مهنة',
  'ta.careerSearch': 'ابحث عن مهنة...',

  // Career Confirmation
  'ta.confirmTitle': 'وجدنا',
  'ta.confirmTitleAccent': 'مهنتك!',
  'ta.confirmSubtitle': 'بناءً على وصفك، هذا ما اكتشفناه.',
  'ta.confirmCareer': 'المهنة المكتشفة',
  'ta.confirmConfidence': 'الثقة',
  'ta.confirmAlternatives': 'اقتراحات أخرى',
  'ta.confirmAccept': 'نعم، هذا صحيح',
  'ta.confirmChange': 'اختر مهنة مختلفة',
  'ta.answeredQuestions': 'المعلومات التي استخرجناها',
  'ta.unmatchedContent': 'تفاصيل إضافية',

  // Missing Questions
  'ta.questionsTitle': 'بعض التفاصيل',
  'ta.questionsTitleAccent': 'الإضافية',
  'ta.questionsSubtitle': 'يرجى ملء المعلومات المتبقية لإكمال ملفك.',

  // Account Details
  'ta.detailsTitle': 'إعداد',
  'ta.detailsTitleAccent': 'ملفك',
  'ta.detailsSubtitle': 'أضف تفاصيلك المهنية.',
  'ta.accountName': 'اسم الملف',
  'ta.accountNamePlaceholder': 'مثال: خدمات الدي جي المميزة',
  'ta.bio': 'نبذة',
  'ta.bioPlaceholder': 'أخبر العملاء عن نفسك...',
  'ta.general': 'عام',
  'ta.contact': 'التواصل',
  'ta.address': 'العنوان',
  'ta.email': 'البريد الإلكتروني',
  'ta.phone': 'الهاتف',
  'ta.phonePlaceholder': 'أدخل رقم الهاتف',
  'ta.addressField': 'العنوان',
  'ta.addressPlaceholder': 'أدخل عنوانك',
  'ta.city': 'المدينة',
  'ta.postalCode': 'الرمز البريدي',
  'ta.postalCodePlaceholder': 'أدخل الرمز البريدي',
  'ta.uploadPhoto': 'رفع صورة',

  // Portfolio
  'ta.portfolioTitle': 'أضف',
  'ta.portfolioTitleAccent': 'معرض أعمالك',
  'ta.portfolioSubtitle': 'اعرض أفضل أعمالك لجذب العملاء.',
  'ta.projectName': 'اسم المشروع',
  'ta.projectNamePlaceholder': 'أدخل اسم المشروع',
  'ta.chooseFile': 'اختر ملف للرفع',
  'ta.addMore': 'أضف المزيد',

  // Verification (Pro)
  'ta.verificationTitle': 'تحقق من',
  'ta.verificationTitleAccent': 'هويتك',
  'ta.verificationSubtitle': 'ارفع المستندات المطلوبة للتحقق من حسابك.',
  'ta.uploadDocument': 'رفع مستند',
  'ta.documentRequired': 'مطلوب',
  'ta.documentOptional': 'اختياري',

  // Subscription (Flex)
  'ta.subscriptionTitle': 'اختر',
  'ta.subscriptionTitleAccent': 'خطتك',
  'ta.subscriptionSubtitle': 'اختر خطة اشتراك لتفعيل حسابك.',
  'ta.perMonth': '/شهر',
  'ta.startTrial': 'ابدأ النسخة التجريبية المجانية',
  'ta.subscribe': 'اشترك الآن',
  'ta.trialDays': 'يوم تجربة مجانية',

  // Completion
  'ta.completeTitle': 'أنت جاهز',
  'ta.completeTitleAccent': 'تمامًا!',
  'ta.completeSubtitle': 'تم إنشاء حسابك المهني بنجاح.',
  'ta.goToWorkspace': 'انتقل إلى مساحة العمل',
  'ta.stayPersonal': 'ابقَ في الوضع الشخصي',

  // Common
  'ta.continue': 'متابعة',
  'ta.skip': 'تخطي',
  'ta.back': 'رجوع',
  'ta.step': 'خطوة',
  'ta.of': 'من',
};
