export default {
  // Profile Screen
  'profile.title': 'الملف الشخصي',
  'profile.menu': 'القائمة',
  'profile.myAccount': 'حسابي',
  'profile.myWallet': 'محفظتي',
  'profile.transactionHistory': 'سجل المعاملات',
  'profile.settings': 'الإعدادات',
  'profile.helpCenter': 'مركز المساعدة',
  'profile.termsAndConditions': 'الشروط والأحكام',
  'profile.logout': 'تسجيل الخروج',
  'profile.professionalAccounts': 'حساباتك المهنية',
  'profile.createAccount': 'إنشاء حساب مهني',
  'profile.noAccounts': 'ليس لديك حسابات مهنية بعد.',
  'profile.switchToPersonal': 'التبديل إلى الشخصي',
  'profile.switchToWorkspace': 'تبديل مساحة العمل',
  'profile.activeWorkspace': 'نشط',
  'profile.requiredDocuments': 'المستندات المطلوبة',
  'profile.addAccount': 'إضافة حساب',
  'profile.account': 'الحساب',
  'profile.accountTab': 'الحساب',
  'profile.documentsTab': 'المستندات',
  'profile.settingsTab': 'الإعدادات',
  'profile.uploadDocument': 'رفع',
  'profile.readyToUpload': 'جاهز',
  'profile.switchingTo': 'التبديل إلى',
  'profile.documents': 'المستندات',
  'profile.continueApplication': 'أكمل طلبك',
  'profile.portfolioTab': 'معرض الأعمال',
  'profile.addPortfolio': 'إضافة مشروع',
  'profile.projectName': 'اسم المشروع',
  'profile.projectNamePlaceholder': 'أدخل اسم المشروع',
  'profile.noPortfolio': 'اعرض أفضل أعمالك لجذب العملاء.',

  // Trading Account Creation — Intro
  'ta.introTitle': 'أنشئ حسابك',
  'ta.introTitleAccent': 'المهني',
  'ta.introSubtitle': 'أعد ملفك المهني وابدأ في تلقي فرص العمل.',
  'ta.introBenefit1': 'احصل على عروض عمل مناسبة',
  'ta.introBenefit2': 'ابنِ معرض أعمالك المهني',
  'ta.introBenefit3': 'أدر حجوزاتك ومدفوعاتك',
  'ta.getStarted': 'ابدأ الآن',

  // AI Input
  'ta.aiTitle': 'أخبرنا عن',
  'ta.aiTitleAccent': 'عملك',
  'ta.aiSubtitle': 'صف ما تفعله وسنقوم بإعداد ملفك تلقائيًا.',
  'ta.aiPlaceholder': 'مثال: أنا دي جي محترف في دبي مع خبرة 5 سنوات...',
  'ta.aiAnalyze': 'تحليل وبناء ملفي',
  'ta.aiManual': 'سأدخل التفاصيل يدويًا',
  'ta.aiCharCount': 'حرف',

  // Career Selection (Manual)
  'ta.careerTitle': 'ما هي مهنتك',
  'ta.careerTitleAccent': 'المثالية؟',
  'ta.careerSubtitle': 'اختر المهنة التي تصف خدماتك المهنية بأفضل شكل.',
  'ta.careerPlaceholder': 'اختر مهنة',
  'ta.careerSearch': 'ابحث عن مهنة...',

  // Career Confirmation
  'ta.confirmTitle': 'وجدنا',
  'ta.confirmTitleAccent': 'مهنتك!',
  'ta.confirmSubtitle': 'بناءً على وصفك، هذا ما اكتشفناه.',
  'ta.confirmCareer': 'المهنة المكتشفة',
  'ta.confirmConfidence': 'الثقة',
  'ta.confirmAlternatives': 'اقتراحات أخرى',
  'ta.confirmAccept': 'نعم، هذا صحيح',
  'ta.confirmChange': 'اختر مهنة مختلفة',
  'ta.answeredQuestions': 'المعلومات التي استخرجناها',
  'ta.unmatchedContent': 'تفاصيل إضافية',

  // Missing Questions
  'ta.questionsTitle': 'بعض التفاصيل',
  'ta.questionsTitleAccent': 'الإضافية',
  'ta.questionsSubtitle': 'يرجى ملء المعلومات المتبقية لإكمال ملفك.',

  // Account Details
  'ta.detailsTitle': 'إعداد',
  'ta.detailsTitleAccent': 'ملفك',
  'ta.detailsSubtitle': 'أضف تفاصيلك المهنية.',
  'ta.accountName': 'اسم الملف',
  'ta.accountNamePlaceholder': 'مثال: خدمات الدي جي المميزة',
  'ta.bio': 'نبذة',
  'ta.bioPlaceholder': 'أخبر العملاء عن نفسك...',
  'ta.general': 'عام',
  'ta.contact': 'التواصل',
  'ta.address': 'العنوان',
  'ta.email': 'البريد الإلكتروني',
  'ta.phone': 'الهاتف',
  'ta.phonePlaceholder': 'أدخل رقم الهاتف',
  'ta.addressField': 'العنوان',
  'ta.addressPlaceholder': 'أدخل عنوانك',
  'ta.city': 'المدينة',
  'ta.postalCode': 'الرمز البريدي',
  'ta.postalCodePlaceholder': 'أدخل الرمز البريدي',
  'ta.uploadPhoto': 'رفع صورة',

  // Portfolio
  'ta.portfolioTitle': 'أضف',
  'ta.portfolioTitleAccent': 'معرض أعمالك',
  'ta.portfolioSubtitle': 'اعرض أفضل أعمالك لجذب العملاء.',
  'ta.projectName': 'اسم المشروع',
  'ta.projectNamePlaceholder': 'أدخل اسم المشروع',
  'ta.chooseFile': 'اختر ملف للرفع',
  'ta.addMore': 'أضف المزيد',

  // Verification (Pro)
  'ta.verificationTitle': 'تحقق من',
  'ta.verificationTitleAccent': 'هويتك',
  'ta.verificationSubtitle': 'ارفع المستندات المطلوبة للتحقق من حسابك.',
  'ta.uploadDocument': 'رفع مستند',
  'ta.documentRequired': 'مطلوب',
  'ta.documentOptional': 'اختياري',

  // Subscription (Flex)
  'ta.subscriptionTitle': 'اختر',
  'ta.subscriptionTitleAccent': 'خطتك',
  'ta.subscriptionSubtitle': 'اختر خطة اشتراك لتفعيل حسابك.',
  'ta.perMonth': '/شهر',
  'ta.startTrial': 'ابدأ النسخة التجريبية المجانية',
  'ta.subscribe': 'اشترك الآن',
  'ta.trialDays': 'يوم تجربة مجانية',

  // Completion
  'ta.completeTitle': 'أنت جاهز',
  'ta.completeTitleAccent': 'تمامًا!',
  'ta.completeSubtitle': 'تم إنشاء حسابك المهني بنجاح.',
  'ta.goToWorkspace': 'انتقل إلى مساحة العمل',
  'ta.stayPersonal': 'ابقَ في الوضع الشخصي',

  // Common
  'ta.continue': 'متابعة',
  'ta.skip': 'تخطي',
  'ta.back': 'رجوع',
  'ta.step': 'خطوة',
  'ta.of': 'من',

  // Portfolio Screen
  'profile.portfolio.title': 'معرض الأعمال',
  'profile.portfolio.addButton': 'إضافة مشروع',
  'profile.portfolio.updateButton': 'تحديث',
  'profile.portfolio.addTitle': 'إضافة مشروع',
  'profile.portfolio.editTitle': 'تعديل المشروع',
  'profile.portfolio.emptyTitle': 'لا توجد مشاريع في معرض الأعمال',
  'profile.portfolio.emptyDescription': 'اعرض أفضل أعمالك بإضافة مشاريع إلى معرضك.',
  'profile.portfolio.deleteConfirmTitle': 'حذف عنصر من المعرض',
  'profile.portfolio.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذا المشروع؟',
  'profile.portfolio.cancel': 'إلغاء',
  'profile.portfolio.delete': 'حذف',
  'profile.portfolio.dateFrom': 'من',
  'profile.portfolio.dateUntil': 'حتى',
  'profile.portfolio.addAccessibility': 'TODO',
  'profile.portfolio.editAccessibility': 'TODO',
  'profile.portfolio.deleteAccessibility': 'TODO',
  'profile.portfolio.validation.titleRequired': 'العنوان مطلوب',
  'profile.portfolio.fields.title': 'العنوان',
  'profile.portfolio.fields.titlePlaceholder': 'مثال: تجديد مطبخ — بوندي',
  'profile.portfolio.fields.description': 'الوصف',
  'profile.portfolio.fields.descriptionPlaceholder': 'صف المشروع ونطاقه ودورك',
  'profile.portfolio.fields.startDate': 'تاريخ البدء',
  'profile.portfolio.fields.endDate': 'تاريخ الانتهاء',
  'profile.portfolio.fields.projectLink': 'رابط المشروع',

  // Experience Screen
  'profile.experience.title': 'الخبرة',
  'profile.experience.addButton': 'إضافة خبرة',
  'profile.experience.updateButton': 'تحديث الخبرة',
  'profile.experience.addTitle': 'إضافة خبرة',
  'profile.experience.editTitle': 'تعديل الخبرة',
  'profile.experience.emptyTitle': 'لم تتم إضافة خبرة بعد',
  'profile.experience.emptyDescription': 'أضف سجل عملك لعرض خلفيتك المهنية.',
  'profile.experience.deleteConfirmTitle': 'حذف الخبرة',
  'profile.experience.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذه الخبرة؟',
  'profile.experience.cancel': 'إلغاء',
  'profile.experience.delete': 'حذف',
  'profile.experience.addAccessibility': 'TODO',
  'profile.experience.addHint': 'TODO',
  'profile.experience.editAccessibility': 'TODO',
  'profile.experience.editHint': 'TODO',
  'profile.experience.deleteAccessibility': 'TODO',
  'profile.experience.deleteHint': 'TODO',
  'profile.experience.validation.title': 'التحقق',
  'profile.experience.validation.jobTitleRequired': 'المسمى الوظيفي مطلوب.',
  'profile.experience.validation.companyRequired': 'الشركة مطلوبة.',
  'profile.experience.validation.startMonthInvalid': 'يجب أن يكون شهر البدء بين 1 و 12.',
  'profile.experience.validation.startYearRequired': 'سنة البدء مطلوبة.',
  'profile.experience.fields.jobTitle': 'المسمى الوظيفي',
  'profile.experience.fields.jobTitlePlaceholder': 'مثال: كهربائي أول',
  'profile.experience.fields.company': 'الشركة',
  'profile.experience.fields.companyPlaceholder': 'مثال: ABC للكهرباء',
  'profile.experience.fields.country': 'البلد',
  'profile.experience.fields.countryPlaceholder': 'مثال: أستراليا',
  'profile.experience.fields.city': 'المدينة',
  'profile.experience.fields.cityPlaceholder': 'مثال: سيدني',
  'profile.experience.fields.startMonth': 'شهر البدء',
  'profile.experience.fields.startYear': 'سنة البدء',
  'profile.experience.fields.endMonth': 'شهر الانتهاء',
  'profile.experience.fields.endYear': 'سنة الانتهاء',
  'profile.experience.fields.monthPlaceholder': '1-12',
  'profile.experience.fields.yearPlaceholder': 'مثال: 2020',
  'profile.experience.fields.currentlyWorkHere': 'أعمل هنا حاليًا',
  'profile.experience.fields.description': 'الوصف',
  'profile.experience.fields.descriptionPlaceholder': 'صف مسؤولياتك...',

  // Education Screen
  'profile.education.title': 'التعليم',
  'profile.education.addButton': 'إضافة تعليم',
  'profile.education.updateButton': 'تحديث التعليم',
  'profile.education.addTitle': 'إضافة تعليم',
  'profile.education.editTitle': 'تعديل التعليم',
  'profile.education.emptyTitle': 'لم يتم إضافة تعليم بعد',
  'profile.education.emptyDescription': 'أضف خلفيتك التعليمية لتعزيز ملفك الشخصي.',
  'profile.education.deleteConfirmTitle': 'حذف التعليم',
  'profile.education.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذا السجل التعليمي؟',
  'profile.education.cancel': 'إلغاء',
  'profile.education.delete': 'حذف',
  'profile.education.addAccessibility': 'TODO',
  'profile.education.addHint': 'TODO',
  'profile.education.editAccessibility': 'TODO',
  'profile.education.editHint': 'TODO',
  'profile.education.deleteAccessibility': 'TODO',
  'profile.education.deleteHint': 'TODO',
  'profile.education.validation.title': 'التحقق',
  'profile.education.validation.institutionRequired': 'المؤسسة مطلوبة.',
  'profile.education.validation.degreeRequired': 'الدرجة العلمية مطلوبة.',
  'profile.education.validation.startYearRequired': 'سنة البدء مطلوبة.',
  'profile.education.fields.country': 'البلد',
  'profile.education.fields.countryPlaceholder': 'مثال: أستراليا',
  'profile.education.fields.institution': 'المؤسسة',
  'profile.education.fields.institutionPlaceholder': 'مثال: جامعة سيدني',
  'profile.education.fields.degree': 'الدرجة العلمية',
  'profile.education.fields.degreePlaceholder': 'مثال: بكالوريوس هندسة',
  'profile.education.fields.startYear': 'سنة البدء',
  'profile.education.fields.startYearPlaceholder': 'مثال: 2018',
  'profile.education.fields.endYear': 'سنة الانتهاء',
  'profile.education.fields.endYearPlaceholder': 'مثال: 2022',

  // Qualifications Screen
  'profile.qualifications.title': 'المؤهلات',
  'profile.qualifications.addButton': 'إضافة مؤهل',
  'profile.qualifications.updateButton': 'تحديث',
  'profile.qualifications.addTitle': 'إضافة مؤهل',
  'profile.qualifications.editTitle': 'تعديل المؤهل',
  'profile.qualifications.emptyTitle': 'لم تتم إضافة مؤهلات بعد',
  'profile.qualifications.emptyDescription': 'أضف الشهادات والجوائز لإبراز خبرتك.',
  'profile.qualifications.deleteConfirmTitle': 'حذف المؤهل',
  'profile.qualifications.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذا المؤهل؟',
  'profile.qualifications.cancel': 'إلغاء',
  'profile.qualifications.delete': 'حذف',
  'profile.qualifications.addAccessibility': 'TODO',
  'profile.qualifications.editAccessibility': 'TODO',
  'profile.qualifications.deleteAccessibility': 'TODO',
  'profile.qualifications.validation.titleRequired': 'اسم الشهادة/الجائزة مطلوب',
  'profile.qualifications.validation.organisationRequired': 'المنظمة مطلوبة',
  'profile.qualifications.validation.yearRequired': 'السنة مطلوبة',
  'profile.qualifications.fields.certificateName': 'اسم الشهادة/الجائزة',
  'profile.qualifications.fields.certificateNamePlaceholder': 'مثال: AWS Certified Solutions Architect',
  'profile.qualifications.fields.organisation': 'المنظمة المانحة',
  'profile.qualifications.fields.organisationPlaceholder': 'مثال: Amazon Web Services',
  'profile.qualifications.fields.summary': 'ملخص',
  'profile.qualifications.fields.summaryPlaceholder': 'وصف موجز للمؤهل',
  'profile.qualifications.fields.year': 'السنة',
  'profile.qualifications.fields.yearPlaceholder': 'مثال: 2023',

  // References Screen
  'profile.references.title': 'المراجع',
  'profile.references.addButton': 'إضافة مرجع',
  'profile.references.updateButton': 'تحديث',
  'profile.references.addTitle': 'إضافة مرجع',
  'profile.references.editTitle': 'تعديل المرجع',
  'profile.references.emptyTitle': 'لم تتم إضافة مراجع بعد',
  'profile.references.emptyDescription': 'أضف مراجع مهنية لبناء الثقة مع العملاء المحتملين.',
  'profile.references.deleteConfirmTitle': 'حذف المرجع',
  'profile.references.deleteConfirmMessage': 'هل أنت متأكد أنك تريد حذف هذا المرجع؟',
  'profile.references.cancel': 'إلغاء',
  'profile.references.delete': 'حذف',
  'profile.references.addAccessibility': 'TODO',
  'profile.references.editAccessibility': 'TODO',
  'profile.references.deleteAccessibility': 'TODO',
  'profile.references.validation.fullNameRequired': 'الاسم الكامل مطلوب',
  'profile.references.validation.relationshipRequired': 'العلاقة مطلوبة',
  'profile.references.validation.contactRequired': 'البريد الإلكتروني أو الهاتف مطلوب',
  'profile.references.validation.companyRequired': 'الشركة مطلوبة لهذه العلاقة',
  'profile.references.validation.jobTitleRequired': 'المسمى الوظيفي مطلوب لهذه العلاقة',
  'profile.references.relationship.manager': 'مدير',
  'profile.references.relationship.colleague': 'زميل',
  'profile.references.relationship.client': 'عميل',
  'profile.references.relationship.friend': 'صديق',
  'profile.references.relationship.other': 'أخرى',
  'profile.references.fields.fullName': 'الاسم الكامل',
  'profile.references.fields.fullNamePlaceholder': 'مثال: جون سميث',
  'profile.references.fields.relationship': 'العلاقة',
  'profile.references.fields.email': 'البريد الإلكتروني',
  'profile.references.fields.emailPlaceholder': 'john@example.com',
  'profile.references.fields.phone': 'الهاتف',
  'profile.references.fields.phonePlaceholder': '+61 400 000 000',
  'profile.references.fields.company': 'الشركة',
  'profile.references.fields.companyPlaceholder': 'مثال: شركة أكمي',
  'profile.references.fields.jobTitle': 'المسمى الوظيفي',
  'profile.references.fields.jobTitlePlaceholder': 'مثال: مطور أول',
  'profile.references.fields.knownSince': 'معروف منذ',
  'profile.references.fields.knownSincePlaceholder': 'مثال: منذ 2019',

  // ── Edit Profile Form ──
  'profile.fields.firstName': 'الاسم الأول',
  'profile.fields.firstNamePlaceholder': 'أدخل الاسم الأول',
  'profile.fields.firstNameRequired': 'الاسم الأول مطلوب',
  'profile.fields.middleName': 'الاسم الأوسط (اختياري)',
  'profile.fields.middleNamePlaceholder': 'أدخل الاسم الأوسط',
  'profile.fields.lastName': 'اسم العائلة',
  'profile.fields.lastNamePlaceholder': 'أدخل اسم العائلة',
  'profile.fields.lastNameRequired': 'اسم العائلة مطلوب',
  'profile.fields.phoneNumber': 'رقم الهاتف',
  'profile.fields.phoneNumberPlaceholder': 'أدخل رقم الهاتف',
  'profile.fields.bio': 'نبذة',
  'profile.fields.bioPlaceholder': 'أخبرنا عن نفسك',
  'profile.fields.gender': 'الجنس (اختياري)',
  'profile.fields.genderPlaceholder': 'اختر الجنس',
  'profile.fields.birthDate': 'تاريخ الميلاد (اختياري)',
  'profile.fields.birthDatePlaceholder': 'اختر تاريخ الميلاد',
  'profile.fields.nationality': 'الجنسية (اختياري)',
  'profile.fields.nationalityPlaceholder': 'مثال: أسترالي',
  'profile.fields.languages': 'اللغات (اختياري)',
  'profile.fields.languageName': 'اللغة',
  'profile.fields.languageNamePlaceholder': 'مثال: العربية، الإنجليزية',
  'profile.fields.proficiency': 'المستوى',
  'profile.fields.isNative': 'لغة أم',
  'profile.gender.male': 'ذكر',
  'profile.gender.female': 'أنثى',
  'profile.proficiency.beginner': 'مبتدئ',
  'profile.proficiency.intermediate': 'متوسط',
  'profile.proficiency.advanced': 'متقدم',
  'profile.proficiency.fluent': 'طلاقة',

  // ── Edit Profile — Address Section ──
  'profile.address.title': 'العناوين',
  'profile.address.type': 'النوع',
  'profile.address.typeRequired': 'النوع مطلوب',
  'profile.address.address': 'العنوان',
  'profile.address.searchPlaceholder': 'ابحث عن عنوان',
  'profile.address.manualEntry': 'أدخل العنوان يدوياً',
  'profile.address.street': 'عنوان الشارع',
  'profile.address.streetPlaceholder': 'أدخل عنوان الشارع',
  'profile.address.streetRequired': 'الشارع مطلوب',
  'profile.address.state': 'الولاية / المنطقة',
  'profile.address.statePlaceholder': 'أدخل الولاية',
  'profile.address.city': 'المدينة',
  'profile.address.cityPlaceholder': 'أدخل المدينة',
  'profile.address.cityRequired': 'المدينة مطلوبة',
  'profile.address.postcode': 'الرمز البريدي',
  'profile.address.postcodePlaceholder': 'الرمز البريدي',
};
